services:
  postgres:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /tank/lulu/volumes/sandbox-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file: ./.env.dc
    networks:
      - sandboxes

  rmq:
    image: rabbitmq:4-management
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - /tank/lulu/volumes/sandbox-rmq/data/:/var/lib/rabbitmq/
      - /tank/lulu/volumes/sandbox-rmq/log/:/var/log/rabbitmq/
    networks:
      - sandboxes

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
    - 6379:6379
    networks:
      - sandboxes

  mongo:
    image: mongo:latest
    restart: always
    hostname: mongodb
    volumes:
      - /tank/lulu/volumes/sandbox-mongo/data/:/data/db/
      - /tank/lulu/volumes/sandbox-mongo/log/:/var/log/mongodb/
    env_file: ./.env.dc
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - sandboxes
  mongo-express:
    image: mongo-express:latest
    restart: always
    env_file: ./.env.dc
    ports:
      - 8081:8081
    depends_on:
      mongo: 
        condition: service_healthy
        restart: true
    networks:
      - sandboxes

  smtp:
    image: bytemark/smtp
    restart: always
    ports:
      - 26:25
      - 466:465
      - 588:587
    env_file: ./.env.dc
    networks:
      - sandboxes


  rust:
    image: sandboxes-rust
    build: ./rust
    env_file: ./rust/.env.dc
    restart: always
    deploy:
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      rmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    networks:
      - sandboxes

  nextjs:
    image: sandboxes-nextjs
    build: ./nextjs
    env_file: ./nextjs/.env.dc
    restart: always
    deploy:
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - sandboxes

  nestjs:
    image: sandboxes-nestjs
    build: ./nestjs
    env_file: ./nestjs/.env.dc
    deploy:
      replicas: 1
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_healthy
        restart: true
    networks:
      - sandboxes

  haskell:
    image: sandboxes-haskell
    build: ./haskell
    # env_file: ./haskell/.env.dc
    deploy:
      replicas: 1
    restart: always
    networks:
      - sandboxes

  angular:
    image: sandboxes-angular
    build: ./angular
    env_file: ./angular/.env.dc
    deploy:
      replicas: 1
    restart: always
    networks:
      - sandboxes

  blazor:
    image: sandboxes-blazor
    build: ./blazor
    # env_file: ./blazor/.env.dc
    deploy:
      replicas: 1
    restart: always
    networks:
      - sandboxes

  go:
    image: sandboxes-go
    build: ./go
    env_file: ./go/.env.dc
    deploy:
      replicas: 1
    # restart: always
    volumes:
      - /tank/lulu/volumes/sandbox-go/logs/:/app/logs
    networks:
      - sandboxes
    depends_on:
      smtp:
        condition: service_started
        restart: true
      rmq:
        condition: service_healthy
        restart: true

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    networks:
      - sandboxes
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rust
      - nextjs
      - nestjs
      - haskell
      - angular

networks:
  sandboxes:
    driver: bridge
    name: sandboxes