# Use postgres/example user/password credentials
# version: '3.9'

services:

  db:
    image: postgis/postgis
    # restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - /tank/lulu/volumes/sandbox-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  rmq:
    image: rabbitmq:4-management
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
      - /tank/lulu/volumes/sandbox-rmq/data/:/var/lib/rabbitmq/
      - /tank/lulu/volumes/sandbox-rmq/log/:/var/log/rabbitmq/

  redis:
    image: redis:latest
    command: redis-server
    ports:
    - 6379:6379

  mongo:
    image: mongo:latest
    hostname: mongodb
    volumes:
      - /tank/lulu/volumes/sandbox-mongo/data/:/data/db/
      - /tank/lulu/volumes/sandbox-mongo/log/:/var/log/mongodb/
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo-admin
    #   MONGO_INITDB_ROOT_PASSWORD: mongo-admin
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongouser
      ME_CONFIG_BASICAUTH_PASSWORD: mongouser
    ports:
      - 8081:8081
    depends_on:
      - mongo
