version: '3.9'

services:

  traefik:
    image: traefik:2.3
    ports:
      - 80:80
      - 8000:8000
    networks:
      - sandboxes

  postgres:
    image: postgis/postgis
    # restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - /tank/lulu/volumes/sandbox-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - sandboxes

  rmq:
    image: rabbitmq:4-management
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
      - /tank/lulu/volumes/sandbox-rmq/data/:/var/lib/rabbitmq/
      - /tank/lulu/volumes/sandbox-rmq/log/:/var/log/rabbitmq/
    networks:
      - sandboxes

  redis:
    image: redis:latest
    command: redis-server
    ports:
    - 6379:6379
    networks:
      - sandboxes

  mongo:
    image: mongo:latest
    hostname: mongodb
    volumes:
      - /tank/lulu/volumes/sandbox-mongo/data/:/data/db/
      - /tank/lulu/volumes/sandbox-mongo/log/:/var/log/mongodb/
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo-admin
    #   MONGO_INITDB_ROOT_PASSWORD: mongo-admin
    ports:
      - 27017:27017
    networks:
      - sandboxes
  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongouser
      ME_CONFIG_BASICAUTH_PASSWORD: mongouser
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - sandboxes

  rust-nginx:
    image: nginx:1.21.6
    links:
      - rust
    volumes:
      - ./rust/default.conf:/etc/nginx/conf.d/default.conf:rw,cached
    labels:
      - traefik.http.routers.rust.rule=Host(`rust.sandboxes.local`)
      - traefik.http.routers.rust.middlewares=rust
      - traefik.http.services.rust.loadbalancer.server.port=80
      - traefik.http.middlewares.rust.headers.customresponseheaders.Access-Control-Allow-Methods=POST, GET, PUT, OPTIONS, DELETE
      - traefik.http.middlewares.rust.headers.customresponseheaders.Access-Control-Allow-Origin=*
      - traefik.http.middlewares.rust.headers.customresponseheaders.Access-Control-Allow-Headers=x-requested-with, Content-Type,Authorization
      - traefik.port=80
    networks:
      - sandboxes

  rust:
    image: sandboxes-rust
    build: ./rust
    ports:
      - 8001:8000
    restart: always
    environment:
      DATABASE_URL: "postgres://rust:rust@sandboxes-postgres-1:5432/rust-db"
      AMQP_URL: "amqp://guest:guest@sandboxes-rmq-1:5672/%2f"
      REDIS_URL: "redis://sandboxes-redis-1:6379"
      SECRET: "shh its a secret"
      RMQ_EXCHANGE: rust
      RUST_BACKTRACE: 1
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: 8000
    depends_on:
      - postgres
      - rmq
      - redis
    networks:
      - sandboxes


networks:
  sandboxes:
    driver: bridge
    name: sandboxes
    external: false