on:
  pull_request:
    paths:
      - 'blazor/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'blazor/**'

name: CI Blazor

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: dotnet build blazor/blazor.sln