on:
  pull_request:
    paths:
      - 'rust/**'
    branches:
      - main
  push:
    branches: 
      - main
    paths:
      - 'rust/**'

name: CD Rust

jobs:
  build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: sandboxes-rust:latest
          file: rust/Dockerfile