on:
  pull_request:
    paths:
      - 'go/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'go/**'

name: CD Go

jobs:
  steps:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: sandboxes-go:latest
          context: "{{defaultContext}}:go"
          cache-from: type=gha
          cache-to: type=gha,mode=max