on:
  pull_request:
    paths:
      - 'go/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'go/**'

name: CI Go

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install
        working-directory: ./go
        run: go get
      - name: Build
        working-directory: ./go
        run: go build