on:
  pull_request:
    paths:
      - 'nestjs/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'nestjs/**'

name: CD NestJs

jobs:
  steps:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Server
        uses: docker/build-push-action@v6
        with:
          tags: sandboxes-nestjs:latest
          context: "{{defaultContext}}:nestjs"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build Worker
        uses: docker/build-push-action@v6
        with:
          tags: sandboxes-nestjs-worker:latest
          context: "{{defaultContext}}:nestjs"
          file: Worker.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max