on:
  pull_request:
    paths:
      - 'nestjs/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'nestjs/**'

name: CI NestJs

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install
        run: npm ci --prefix nestjs
      - name: Build
        run: npm run build --prefix nestjs
      - name: Test
        run: npm run test --prefix nestjs
      - name: Lint
        run: npm run lint:check --prefix nestjs
      - name: Fmt
        run: npm run format:check --prefix nestjs