on:
  pull_request:
  push:
    branches: main
  paths:
    - nestjs/**

name: CI NestJs

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci --prefix nestjs
      - run: npm run build --prefix nestjs
      - run: npm run lint:check --prefix nestjs
      - run: npm run format:check --prefix nestjs