on:
  pull_request:
    paths:
      - 'nextjs/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'nextjs/**'

name: CI NextJs

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install
        run: npm ci --prefix nextjs
      - name: Build
        run: npm run build --prefix nextjs -- --experimental-build-mode compile
      - name: Test
        run: npm run test --prefix nextjs
      - name: Lint
        run: npm run lint --prefix nextjs
      - name: Fmt
        run: npm run format:check --prefix nextjs