on:
  pull_request:
    paths:
      - 'nextjs/**'
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'nextjs/**'

name: CD NextJs

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Server
        uses: docker/build-push-action@v6
        with:
          tags: sandboxes-nextjs:latest
          context: "{{defaultContext}}:nextjs"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build Worker
        uses: docker/build-push-action@v6
        with:
          tags: sandboxes-nextjs-worker:latest
          context: "{{defaultContext}}:nextjs"
          dockerfile: Worker.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max