on:
  pull_request:
    paths:
      - 'rust/**'
    branches:
      - main
  push:
    branches: 
      - main
    paths:
      - 'rust/**'

name: CI Rust

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install target wasm32
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
          targets: "wasm32-unknown-unknown"

  build-server:
    needs: setup
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - name: Build Server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --bins --manifest-path rust/Cargo.toml

  build-worker:
    needs: setup
    name: Build Worker
    runs-on: ubuntu-latest
    steps:
      - name: Build Worker
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin worker --features rmqsub --no-default-features --locked --manifest-path rust/Cargo.toml

  build-app:
    needs: setup
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Build App Frontend
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package shell --lib --target wasm32-unknown-unknown --features=appcsr --no-default-features --locked --manifest-path rust/Cargo.toml
      - name: Build App Backend
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package shell --bin shell --features appssr --no-default-features --locked --manifest-path rust/Cargo.toml

  checks:
    needs: setup
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rust/Cargo.toml
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path rust/Cargo.toml -- --check