on:
  pull_request:
    paths:
      - 'rust/**'
    branches:
      - main
  push:
    branches: 
      - main
    paths:
      - 'rust/**'

name: CI Rust

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --bins --manifest-path rust/Cargo.toml
      - name: Build Worker
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin worker --features rmqsub --no-default-features --locked --manifest-path rust/Cargo.toml
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rust/Cargo.toml
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path rust/Cargo.toml -- --check